import { Roboto_Condensed, Whisper } from "next/font/google";
import Image from "next/image";
import { FaComments, FaQuestion } from "react-icons/fa";
import { MdAttachEmail } from "react-icons/md";
import { PiCoatHangerFill } from "react-icons/pi";
import "./globals.css";

const inter = Whisper({ subsets: ["latin"], weight: ["400"] });
const roboto = Roboto_Condensed({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Clark Fusion",
  description: "Generated by Djaouad",
  icons: {
    icon: '/favicon.ico', // Add favicon
  },
  viewport: 'width=device-width, initial-scale=1.0', // Add viewport meta tag
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content={metadata.viewport} />
        <link rel="icon" href={metadata.icons.icon} />
        {/* You can add other meta tags here as needed */}
      </head>
      <body className={`${roboto.className} w-full min-h-screen bg-slate-100`}>
        {children}
      </body>
    </html>
  );
}
